<?php 

/*
* Implements hook_preprocess_HOOK()
*/
function codetuts_preprocess_block(&$variables) {
	if (!empty($variables['elements']['#id'])) 
	{
		$block = Drupal\block\Entity\Block::load($variables['elements']['#id']);

		if($block->getRegion() == "sidebar_second")
		{
			$variables["attributes"]["class"][] = "card";
		}
	}
}


function codetuts_views_pre_render_front_page(ViewExecutable $view) {
	var_dump("lol");
}